### ISSUE TITLE
¿Por que ToInt?

### ISSUE THREAD

**Issue by delucas** [AlanJZarate/AyP2---TP#3]
https://github.com/AlanJZarate/AyP2---TP/blob/f66139963ae8664b5007477a35f542100531aa53/Competidor.java#L12

**Comment by AlanJZarate** [comment]
Acá xq vimos que por convención los diccionarios se suelen nombrar con el nombre de la key To Value

**Comment by LionelErasUNTREF** [comment]
quizás sería "caracteristicasToValue"? Es por lo que comenta @AlanJZarate : investigamos un poco y suele usarse [key]To[value] para nombre de Mapas/Diccionarios. Proponés algún otro nombre, @delucas ?

**Comment by delucas** [comment]
No propongo nada en particular jaja. Pero es raro el nombre, develando un detalle de implementación. Me gusta más el nombre propuesto por Lionel. Y si estuviera todo en el mismo idioma, mejor ;)

**Comment by LionelErasUNTREF** [comment]
Se modifico el nombre a "caracteristicaAValor"
